### ISSUE TITLE
Authentication Login Screen

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#12]
## Task(s)
- [ ]

**Comment by PawanKolhe** [comment]
**Login / Signup flow:**  
- User clicks `Login with Discord` button
- Check if user already in DB using email property
  - If Yes, give fellow access to Dashboard. End.
  - If No, proceed to next step.
- Check if fellow in `MLH Fellowship` discord server/guild.
  - If No, throw 4XX error `User not in MLH Fellowship Discord server`. Back to Login page.
  - If Yes, proceed to sign-up page.
- Sign-up page: Discord username (OAuth), email (OAuth), pod (dropdown), role (fellow/admin).
- If admin role selected, check for `Fellow Central Admin` tag on `MLH Fellowship` server/guild.
  - If not found, throw error 4XX `You need the 'Fellow Central Admin' tag to signup as Admin`.
  - If found, complete sign-up. Open Admin Dashboard. End.
- Complete sign-up. Open Fellow Dashboard. End.

> Note: make a new discord guild instead of the `MLH Fellowship` guild for testing our app.
