### ISSUE TITLE
User Data Model

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#16]
## Task(s)
- [ ] Model the User schema in the database
- [ ] Fields: userId (discord tag), name (display name), role (admin/fellow), pod, points, email

**Comment by PawanKolhe** [comment]
@cqvu @boyuan12 I think the `email` field should be included here. If we add different authentication methods in the future, email is something that would be used to uniquely identify a user. What do you think?

**Comment by boyuan12** [comment]
Sure, it's really just a row anyway, and seems like pretty easy to fetch from Discord anyway.
Thanks,Boyuan
    On Monday, March 8, 2021, 10:44:27 PM PST, Pawan Kolhe <notifications@github.com> wrote:  
 
 


@cqvu @boyuan12 I think the email field should be included here. If we add different authentication methods in the future, email is something that would be used to uniquely identify a user. What do you think?
