### ISSUE TITLE
Events Data Model

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#17]
## Task(s)
- [ ] Fields: name, link, start/end time, points, secret code, description

**Comment by luiszugasti** [comment]
Just a comment about the Description field. I think to keep it simple I can have a wide varchar field, but I feel that making a reference to an actual textfile/blob _outside_ of the database would be a more professional way to do it.

However I **don't** know how to do that, so for now this is a bit of a pipe dream :)
