### ISSUE TITLE
Get Events

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#31]
## Task(s)
- [ ] Get all events 
- [ ] If user is a fellow, don't return secret code

**Comment by luiszugasti** [comment]
Yeah, I don't know what this refers to - Get all events? Like the descriptions? @cqvu

**Comment by PawanKolhe** [comment]
@luiszugasti This is for getting all events that are in the DB to display on Events page for the fellow.

![image](https://user-images.githubusercontent.com/8324407/110896792-48e49a00-8322-11eb-83b8-a3fd8247a5fa.png)

**Comment by luiszugasti** [comment]
Ok - I'll work on getting #32 and #33 done and if this issue is still up I'll also implement that
