### ISSUE TITLE
Get points for User

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#34]
## Task(s)
- [ ]

**Comment by luiszugasti** [comment]
From the discord convo, we will be removing the "points_total" column from users.

Anyways, this is very similar to do from the case in #33.

Mock for how to do it in SQLAlchemy (with SQL code):

SELECT * FROM points p LEFT JOIN users u ON u.id = p.assignee WHERE u.name=${user_to_query};

where the user to query is a get parameter from the endpoint call.

I should note that we have to then aggregate on the p.amount column

Again then wrapping it up nicely in a JSON object to be consumed by the front end.
