### ISSUE TITLE
Get list of 20 most recent points from Points

### ISSUE THREAD

**Issue by PawanKolhe** [MLH-Fellowship/fellow-central#47]
## Task(s)
- [ ] Get list of 20 most recent points object transactions from Points

![image](https://user-images.githubusercontent.com/8324407/110896449-a75d4880-8321-11eb-8d79-00837f23d1f6.png)

**Comment by luiszugasti** [comment]
you got it.

**Comment by cqvu** [comment]
> you got it.

yup just sent in a PR for it
